# Netlify Configuration
[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# Environment variables for production
[build.environment]
  VITE_SERVER_URL = "https://gambling-app-backend.onrender.com"
  VITE_APP_ENV = "production"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"